#!/usr/bin/env bash
# Configures Nginx with a custom X-Served-By header containing the hostname

apt-get update
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

sed -i "/listen 80 default_server;/a \\\tadd_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-available/default

service nginx restart