#!/usr/bin/env bash
# Installs and configures HAProxy as a round-robin load balancer

apt-get update
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8 -y
apt-get update
apt-get install -y haproxy=2.8.\*

cat > /etc/haproxy/haproxy.cfg << 'EOF'
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
	timeout connect 5000
	timeout client  50000
	timeout server  50000

frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server 7077-web-01 44.211.165.16:80 check
	server 7077-web-02 54.236.220.142:80 check
EOF

echo "ENABLED=1" > /etc/default/haproxy

service haproxy restart