#!/usr/bin/env bash
# Installs nginx and configures /redirect_me as a 301 redirect

apt-get update
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

sed -i '/listen 80 default_server;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default

service nginx restart